#
# Video processing image for the IDInteraction object tracking pipeline.
#
# Robert Haines, University of Manchester.
#

FROM idinteraction/base

MAINTAINER Robert Haines <robert.haines@manchester.ac.uk>

RUN apt-get install -y mencoder && apt-get clean
